defaults:
  - analytics: "default"
  - _self_

experiment_name: "fmg-ctct-2"
mlflow_tracking_uri: "sqlite:///mlflow.db"
analytics_experiment_name: "${experiment_name}-analytics"

hydra:
  run:
    dir: hydra/outputs/analytics/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: hydra/multirun/analytics/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false
