defaults:
  - data: "sp500-crsp-compustat"
  - preprocessing: "sp500-crsp-compustat"
  - features: "fmg-features"
  - masking: "sp500-membership"
  - loss: null
  - model: null
  - training: null
  - hyperparameter_selection: null
  - recovery: "off"
  - split: "single_split"
  - experiment: "fmg-clstm"
  - _self_

calendar: "XNYS"
trading_year: 252

mlflow_tracking_uri: "sqlite:///mlflow.db"

hydra:
  run:
    dir: hydra/outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: hydra/multirun/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false
